# Generated by Django 3.2.10 on 2022-06-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'WITHDRAWAL'), ('DEPOSIT', 'DEPOSIT')], default='DEPOSIT', max_length=20, verbose_name='TRANSACTION TYPE')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
