# Generated by Django 3.2.10 on 2022-06-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220628_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
